pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash
        strict: true
        strict_method: rebase
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
  - name: automatic merge for pyUp pull requests
    conditions:
      - author=pyup-bot
      - status-success=Travis CI - Pull Request
      - label=update
    actions:
      merge:
        method: merge
