rules:
  default:
    disabling_label: no-mergify
    merge_strategy:
        method: squash
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_status_checks:
        contexts:
        - continuous-integration/travis-ci
