pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - status-success=build (3.7)
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - "#commented-reviews-by=0"
      - label=ready-to-merge
    actions:
      merge:
        method: squash
        strict: true
        strict_method: rebase
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
  - name: automatic merge for pyUp pull requests
    conditions:
      - author=pyup-bot
      - status-success=build (3.7)
      - label=dependencies
    actions:
      merge:
        method: squash
        strict: true
        strict_method: rebase
  - name: automatic merge for dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=build (3.7)
      - label=dependencies
    actions:
      merge:
        method: squash
        strict: true
        strict_method: rebase
