pull_request_rules:
  - name: automatic merge for pyUp pull requests
    conditions:
      - author=pyup-bot
      - status-success=Python application / build (3.7) (push)
      - label=update
    actions:
      merge:
        method: squash
        strict: true
        strict_method: rebase
  - name: automatic merge on CI success and review
    conditions:
      - status-success=Python application / build (3.7) (push)
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash
        strict: true
        strict_method: rebase
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
